version: '3.1'

services:
  frontend:
    build: ./frontend
    restart: always
    env_file:
      - ./frontend/.env
    ports:
      - 3000:3000
    volumes:
      - type: bind
        source: ./frontend
        target: /frontend
    depends_on:
      - backend
  backend:
    build: ./backend
    restart: always
    env_file:
      - ./backend/.env
    ports:
      - 5000:5000
    volumes:
      - type: bind
        source: ./backend
        target: /backend
    depends_on:
      - db
  db:
    image: postgres:15.4
    restart: always
    env_file:
      - ./database/.env
    ports:
      - 8000:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
  
volumes:
  pgdata:
